package org.itson.disenosw.guis;

/**
 *
 * @author Roberto García
 */
public class PanelMenu2 extends javax.swing.JPanel {

    private final FramePrincipal framePrincipal;
    
    /** Creates new form PanelMenu2
     * @param framePrincipal */
    public PanelMenu2(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarrito = new javax.swing.JButton();
        btnProducto1 = new javax.swing.JButton();
        btnProducto2 = new javax.swing.JButton();
        btnProducto3 = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarrito.setBorder(null);
        btnCarrito.setContentAreaFilled(false);
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 60, 60));

        btnProducto1.setBorder(null);
        btnProducto1.setContentAreaFilled(false);
        btnProducto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto1ActionPerformed(evt);
            }
        });
        add(btnProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 370, 100));

        btnProducto2.setBorder(null);
        btnProducto2.setContentAreaFilled(false);
        btnProducto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto2ActionPerformed(evt);
            }
        });
        add(btnProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, 370, 100));

        btnProducto3.setBorder(null);
        btnProducto3.setContentAreaFilled(false);
        btnProducto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto3ActionPerformed(evt);
            }
        });
        add(btnProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 450, 370, 100));

        btnRetroceder.setBorder(null);
        btnRetroceder.setContentAreaFilled(false);
        btnRetroceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelMenu2.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        framePrincipal.setIdProducto(1l);
        framePrincipal.cambiarVistaCarrito();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto1ActionPerformed
        framePrincipal.setIdProducto(1l);
        framePrincipal.cambiarVistaProducto();
    }//GEN-LAST:event_btnProducto1ActionPerformed

    private void btnProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto2ActionPerformed
        framePrincipal.setIdProducto(2l);
        framePrincipal.cambiarVistaProducto();
    }//GEN-LAST:event_btnProducto2ActionPerformed

    private void btnProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto3ActionPerformed
        framePrincipal.setIdProducto(3l);
        framePrincipal.cambiarVistaProducto();
    }//GEN-LAST:event_btnProducto3ActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        framePrincipal.cambiarVistaMenu();
    }//GEN-LAST:event_btnRetrocederActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnProducto1;
    private javax.swing.JButton btnProducto2;
    private javax.swing.JButton btnProducto3;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

}
