package GUI;

/**
 * Esta clase representa la vista de inicio de sesión en la interfaz gráfica del
 * banco. Permite a los usuarios iniciar sesión proporcionando su nombre de
 * usuario y contraseña.
 */
public class PanelMenu extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;

    /**
     * Constructor de la clase VistaInicioSesion.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public PanelMenu(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCarrito = new javax.swing.JButton();
        btnProducto1 = new javax.swing.JButton();
        btnProducto2 = new javax.swing.JButton();
        btnProducto3 = new javax.swing.JButton();
        btnProducto4 = new javax.swing.JButton();
        btnAvanzar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setPreferredSize(new java.awt.Dimension(400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarrito.setBorder(null);
        btnCarrito.setContentAreaFilled(false);
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        add(btnCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 60, 60));

        btnProducto1.setBorder(null);
        btnProducto1.setContentAreaFilled(false);
        btnProducto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto1ActionPerformed(evt);
            }
        });
        add(btnProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 188, 370, 100));

        btnProducto2.setBorder(null);
        btnProducto2.setContentAreaFilled(false);
        btnProducto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto2ActionPerformed(evt);
            }
        });
        add(btnProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 298, 370, 100));

        btnProducto3.setBorder(null);
        btnProducto3.setContentAreaFilled(false);
        btnProducto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto3ActionPerformed(evt);
            }
        });
        add(btnProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 408, 370, 100));

        btnProducto4.setBorder(null);
        btnProducto4.setContentAreaFilled(false);
        btnProducto4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProducto4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducto4ActionPerformed(evt);
            }
        });
        add(btnProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 518, 370, 100));

        btnAvanzar.setBorder(null);
        btnAvanzar.setContentAreaFilled(false);
        btnAvanzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvanzarActionPerformed(evt);
            }
        });
        add(btnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 60, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelMenu.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto1ActionPerformed
        FramePrincipal framePrincipal2 = new FramePrincipal(1);
        this.framePrincipal = framePrincipal2;
        framePrincipal.cambiarVistaProducto();
    }//GEN-LAST:event_btnProducto1ActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        framePrincipal.cambiarVistaCarrito();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnProducto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto2ActionPerformed
        FramePrincipal framePrincipal2 = new FramePrincipal(2);
        framePrincipal2.cambiarVistaProducto();

    }//GEN-LAST:event_btnProducto2ActionPerformed

    private void btnProducto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto3ActionPerformed
        FramePrincipal framePrincipal2 = new FramePrincipal(3);
        framePrincipal2.cambiarVistaProducto();

    }//GEN-LAST:event_btnProducto3ActionPerformed

    private void btnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvanzarActionPerformed
        framePrincipal.cambiarPanelMenu2();
    }//GEN-LAST:event_btnAvanzarActionPerformed

    private void btnProducto4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducto4ActionPerformed
        FramePrincipal framePrincipal2 = new FramePrincipal(4);
        framePrincipal2.cambiarVistaProducto();

    }//GEN-LAST:event_btnProducto4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanzar;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnProducto1;
    private javax.swing.JButton btnProducto2;
    private javax.swing.JButton btnProducto3;
    private javax.swing.JButton btnProducto4;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
