package org.itson.disenosw.guis;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Esta clase representa la vista de inicio de sesión en la interfaz gráfica del
 * banco. Permite a los usuarios iniciar sesión proporcionando su nombre de
 * usuario y contraseña.
 */
public class PanelPagoExitoPuntos extends javax.swing.JPanel {

    private FramePrincipal ventana;

    /**
     * Constructor de la clase VistaInicioSesion.
     *
     * @param ventana La ventana principal de la aplicación.
     */
    public PanelPagoExitoPuntos(FramePrincipal ventana) {
        this.ventana = ventana;
        initComponents();

    }

    public PanelPagoExitoPuntos(FramePrincipal ventana, Integer puntosGenerados, String numPedido, String claveRecoger) {
        try {
            this.ventana = ventana;
            initComponents();

            lblPuntosGenerados.setText(puntosGenerados.toString() + " puntos");
            lblClaveRecoger.setText(claveRecoger);
            lblNumPedido.setText(numPedido);
        } catch (Exception ex) {
            Logger.getLogger(PanelPagoExitoPuntos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuntosGenerados = new javax.swing.JLabel();
        lblClaveRecoger = new javax.swing.JLabel();
        lblNumPedido = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setPreferredSize(new java.awt.Dimension(400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lblPuntosGenerados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 230, 30));
        add(lblClaveRecoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 230, 30));
        add(lblNumPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelPagoExitoPuntos.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblClaveRecoger;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblPuntosGenerados;
    // End of variables declaration//GEN-END:variables
}
