package org.itson.disenosw.guis;

import SubsistemaCIA.IValidarPersona;
import SubsistemaCIA.ValidarPersona;
import java.util.List;
import javax.swing.JOptionPane;
import mocks.Usuario;
import org.itson.disenosw.dtos.UsuarioDTO;

/**
 * Esta clase representa la vista de inicio de sesión en la interfaz gráfica del
 * banco. Permite a los usuarios iniciar sesión proporcionando su nombre de
 * usuario y contraseña.
 */
public class PanelInicioSesion extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;
    private Usuario usuario = new Usuario();

    /**
     * Constructor de la clase VistaInicioSesion.
     *
     * @param framePrincipal La framePrincipal principal de la aplicación.
     */
    public PanelInicioSesion(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        usuario.generarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 30));

        btnIngresar.setBorder(null);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, 53));

        txtContraseña.setBorder(null);
        add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 340, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelInicioSesion.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (txtID.getText().isBlank() || txtContraseña.getPassword().length == 0) {
            framePrincipal.mostrarAviso("Es necesario llenar todos los campos", "Campos inválidos");
        } else {
            List<Usuario> usuarios = usuario.getListaUsuarios();
            IValidarPersona vp = new ValidarPersona();
            //TODO
            //la contraseña no se debería mandar como string
            //el metodo validar persona debería lanzar excepcion y cacharse aquí
            UsuarioDTO u = new UsuarioDTO(new String(txtContraseña.getPassword()),txtID.getText());
            if (vp.ValidarPersona(u)) {
                framePrincipal.cambiarVistaMenu();
            } else {
                framePrincipal.mostrarAviso("No se encontró un usuario con\nlas credenciales proporcionadas", "Usuario inválido");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
