package org.itson.disenosw.guis;

/**
 *
 * @author Roberto García
 */
public class PanelBuscar extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;
    /** Creates new form PanelBuscar */
    public PanelBuscar(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelBuscar.png"))); // NOI18N
        add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBuscar;
    // End of variables declaration//GEN-END:variables

}
